"""Rename name column to description

Revision ID: 55de83e4be1c
Revises: 
Create Date: 2024-06-30 21:55:28.039440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55de83e4be1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
